version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
  cassandra:
    hostname: cassandra
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let the system to catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    # volumes: #uncomment if you desire mounts, uncomment cluster.sh
    #   - ./data/cassandra:/var/lib/cassandra:rw
